### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by cp2587** [wiremind/super-bowl#24]
We should have a paging for every view in order to avoid pulling too many tasks (on a typical application, we have more than thousands of tasks created every 5 mins)

**Comment by cp2587** [comment]
What do you suggest ? 
I like the idea to have 24-hours of task states, it seems reasonnable.

**Comment by antoinerabany** [comment]
We already keep 24h of state, I was a asking if you were willing to reduce this

We could do pagination and sorting in the backend, I looked at flower that's how they do it.
I would mean query all states, filter and sort them.

We will see in utilisation if it cause problems, but this should be ok.

**Comment by cp2587** [comment]
yes i understood about the 24h :rabbit:  - but i think reducing it would not be wise (24h is reasonnable as you will see all scheduled task).

I agree, we can start by doing something simple as you described - maybe just implement a hard limit in the backend (for instance work on at most 100k task, above you can warn the user in the front that he should change the expiry time for the states to avoid keeping too many of them)
