### ISSUE TITLE
Display results if task is finished

### ISSUE THREAD

**Issue by xdanielsb** [wiremind/super-bowl#43]
In some cases could be useful if the task is finished display the results in the interface.

**Comment by antoinerabany** [comment]
put it here [
![Untitled](https://user-images.githubusercontent.com/6851979/88184399-ede72100-cc32-11ea-84d0-a602675f4bc6.png)
](url)

also you need to be careful with the size of the response, results can be huge ! set a smart limit.
Also there could be serialization problems too.
